name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Git repositorydan kodni olish
    - name: Checkout repository
      uses: actions/checkout@v3

    # Python-ni o'rnatish
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.6

    # Kutubxonalarni o'rnatish
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Django migratsiyalarni qo'llash
    - name: Apply migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate

    # Django testlarni ishga tushirish
    - name: Run tests
      run: |
        python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Git repositorydan kodni olish
    - name: Checkout repository
      uses: actions/checkout@v3

    # Python-ni o'rnatish
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.6

    # Kutubxonalarni o'rnatish
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Django loyihasini ishga tushirish uchun serverni sozlash
    - name: Deploy Django App
      env:
        DJANGO_SETTINGS_MODULE: wanderlust_backend.settings
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: 'False'
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      run: |
        python manage.py collectstatic --noinput
        python manage.py migrate
        gunicorn your_project.wsgi:application --bind 0.0.0.0:8000
